### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by ThiagoSousaSantana** [ThiagoSousaSantana/groceries#8]
A autenticação via **Google**, **Apple**, e outros provedores de login (conhecida como **OAuth2** ou **OpenID Connect**) envolve tanto o **frontend** quanto o **backend**.

### Como funciona o fluxo de autenticação OAuth2:

1. **Frontend** (Next.js):
   - O usuário clica em um botão para fazer login com Google, Apple, etc.
   - O frontend redireciona o usuário para o provedor de identidade (Google, Apple), onde ele autoriza a aplicação a acessar suas informações.
   - Após a autorização, o provedor redireciona de volta para sua aplicação com um **código de autorização** (ou **token**) na URL.

2. **Backend** (Spring):
   - O backend recebe esse código e o utiliza para obter um **access token** do provedor.
   - Com esse access token, o backend pode solicitar informações do usuário ao provedor de identidade (como nome, e-mail, etc.).
   - O backend valida e processa os dados do usuário e retorna uma sessão de login ou um token JWT para o frontend.

### Implementação com **Spring** no Backend

No Spring, você pode usar a biblioteca **Spring Security** junto com a dependência **Spring OAuth2 Client** para facilitar a integração com provedores OAuth2.

#### Dependências Maven:
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-oauth2-client</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
```

#### Configurando o login OAuth2 em Spring:
```yaml
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          apple:
            client-id: YOUR_APPLE_CLIENT_ID
            client-secret: YOUR_APPLE_CLIENT_SECRET
            scope: name, email
            redirect-uri: "{baseUrl}/login/oauth2/code/apple"
```

#### Controlador para lidar com redirecionamento e autenticação:
O Spring Security cuida automaticamente do redirecionamento para o provedor OAuth2 e do retorno ao backend com o código de autorização.

#### Autenticação no Backend (JWT, Sessões):
Você pode usar o Spring Security para configurar JWT ou sessões no backend, armazenando a autenticação no cliente.

### Implementação com **Next.js** no Frontend

No frontend, você pode usar o pacote **NextAuth.js**, que facilita muito a integração com provedores OAuth2 como Google e Apple. O NextAuth lida com a autenticação no lado do frontend e faz chamadas ao backend para validar as informações.

#### Dependências:
Instale o NextAuth:
```bash
npm install next-auth
```

#### Configurando NextAuth para Google e Apple:
No arquivo `[...nextauth].js` (ou `.ts`):
```javascript
import NextAuth from "next-auth";
import GoogleProvider from "next-auth/providers/google";
import AppleProvider from "next-auth/providers/apple";

export default NextAuth({
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    }),
    AppleProvider({
      clientId: process.env.APPLE_CLIENT_ID,
      clientSecret: process.env.APPLE_CLIENT_SECRET
    })
  ],
  callbacks: {
    async jwt(token, user) {
      if (user) {
        token.id = user.id;
      }
      return token;
    },
    async session(session, token) {
      session.user.id = token.id;
      return session;
    }
  }
});
```

### Fluxo Final:

1. O **Next.js** (frontend) fornece a interface para o usuário se autenticar.
2. O backend Spring Security gerencia a autenticação e autorização dos provedores OAuth.
3. O backend armazena ou valida as credenciais do usuário.
4. O frontend recebe tokens (JWT ou sessão) para autorizar futuras interações com o backend.

Esse fluxo combina o **Next.js** para a interface de login e o **Spring** no backend para manipular a autenticação e autorização com segurança.
